#!/usr/bin/env python3

# vim: ft=python
# ========================================================================
# Bully Build System - is a simple helper script
# for building Unity projects
# ========================================================================
# Written with care by Bully developers using Dvorak layout in 2016

"""Lena

Usage:
    lena build <profile>
    lena --version

Options:
    -h --help   Show this screen.
    --version   Show version.

"""

import sys
from docopt import docopt

def main():
    arguments = docopt(__doc__, version='Lena 0.0.1')
    print (arguments)

if __name__ == "__main__":
    main()
