#!/usr/bin/env python3

# vim: ft=python
# ========================================================================
# Bully Build System - is a simple helper script
# for building Unity projects
# ========================================================================
# Written with care by Bully developers using Dvorak layout in 2016

import sys

def main():
  print ('Hello from Lena')
  # Command line args are in sys.argv[1], sys.argv[2] ..
  # sys.argv[0] is the script name itself and can be ignored

if __name__ == "__main__":
    main()
